name: spacex_api_models
description: A package containing the models used for the spacex api.
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  freezed: ^2.3.3
  freezed_annotation: ^2.2.0

dev_dependencies:
  json_serializable: ^6.6.2
  build_runner: ^2.3.3